alias: Battery Disabled Fix
description: ""
trigger:
  - platform: state
    entity_id:
      - select.solaredge_storage_control_mode
    to: Disabled
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: input_select.desired_battery_mode
        state: Disabled
action:
  - service: notify.mobile_app_pixel_5
    data:
      title: Battery Disabled
      message: >-
        Battery has changed to disabled mode unexpectedly. Will try to re-enable
        unless cancelled.
      data:
        actions:
          - action: FIX
            title: Fix
          - action: CANCEL
            title: Cancel
  - alias: Wait for a response
    wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: CANCEL
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: FIX
    timeout:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
    continue_on_timeout: true
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ wait.trigger.event.data.action == \"CANCEL\" }}"
            alias: Cancel
        sequence: null
      - conditions:
          - condition: template
            value_template: "{{ wait.trigger.event.data.action == \"FIX\" }}"
        sequence:
          - repeat:
              until:
                - condition: state
                  entity_id: select.solaredge_storage_control_mode
                  state: Time of Use
                  for:
                    hours: 0
                    minutes: 5
                    seconds: 0
              sequence:
                - service: select.select_option
                  data:
                    option: Time of Use
                  target:
                    entity_id: select.solaredge_storage_control_mode
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 30
                    milliseconds: 0
      - conditions:
          - condition: template
            value_template: "{{ not wait.trigger }}"
        sequence:
          - repeat:
              until:
                - condition: state
                  entity_id: select.solaredge_storage_control_mode
                  state: Time of Use
                  for:
                    hours: 0
                    minutes: 5
                    seconds: 0
              sequence:
                - service: select.select_option
                  data:
                    option: Time of Use
                  target:
                    entity_id: select.solaredge_storage_control_mode
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 30
                    milliseconds: 0
mode: single
