alias: Octopus Saving Session Auto enroll
description: Opt-in and add to calendar
trigger:
  - platform: event
    event_type: octopus_energy_new_octoplus_saving_session
    alias: Octopus Saving Session Discovered
    id: Saving Session Event
condition: []
action:
  - service: calendar.create_event
    target:
      entity_id: calendar.saving_sessions
    data:
      summary: >-
        Saving Session {{ trigger.event.data['event_octopoints_per_kwh'] }}
        points/kWh
      start_date_time: "{{ trigger.event.data[\"event_start\"] }}"
      end_date_time: "{{ trigger.event.data[\"event_end\"] }}"
    alias: Schedule Session in calendar
  - service: octopus_energy.join_octoplus_saving_session_event
    data:
      event_code: "{{ trigger.event.data[\"event_code\"] }}"
    target:
      entity_id: event.octopus_energy_a_87733097_octoplus_saving_session_events
    alias: Opt-in to Saving Session
  - service: notify.mobile_app_pixel_5
    data:
      message: >
        New Octopus Energy saving session. It starts at {{
        trigger.event.data["event_start"].strftime('%H:%M') }} on {{
        trigger.event.data["event_start"].day }}/{{
        trigger.event.data["event_start"].month }}
    alias: Notify Pixel 5
mode: single
